{% set name = "htgettoken" %}
{% set version = "1.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/fermitools/htgettoken/archive/v{{ version }}.tar.gz
  sha256: 04c694eef09edd3b89d9938adeb3b8ec10d1297c7a93295c72837ae030b9d9f7

build:
  number: 0
  skip: true  # [win]

requirements:
  host:
    - python
  run:
    - m2crypto
    - paramiko
    - pykerberos  # [not win]
    - pyopenssl
    - python
    - winkerberos  # [win]

test:
  commands:
    - htgettoken --help

about:
  home: https://github.com/fermitools/htgettoken
  dev_url: https://github.com/fermitools/htgettoken.git
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  summary: Get OIDC bearer tokens by interacting with Hashicorp vault
  description: |
    htgettoken gets OIDC bearer tokens by interacting with Hashicorp vault

extra:
  recipe-maintainers:
    - duncanmmacleod
