{% set name = "htgettoken" %}
{% set version = "2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/fermitools/htgettoken/archive/v{{ version }}.tar.gz
  sha256: 6c14bbc8909d5ecd3fd21a4bef92334aa353a9f8d5ae73d7c42edf1caa37b0b9

build:
  entry_points:
    - htgettoken = htgettoken:main
  noarch: python  # [win]
  number: 1
  script: {{ PYTHON }} -m pip install . -vv  # [win]

requirements:
  build:
    - python                              # [unix and build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [unix and build_platform != target_platform]
  host:
    - pip
    - python  # [unix]
    - python >=3.5  # [win]
    - setuptools >=30.3.0
    - wheel
  run:
    - __win  # [win]
    - jq  # [unix]
    - paramiko
    - python  # [unix]
    - python >=3.5  # [win]
    - python-gssapi
    - urllib3

test:
  requires:
    - pip
  imports:
    - htgettoken
  commands:
    # check metadata
    - python -m pip check
    - python -m pip show htgettoken
    # test scripts
    - htgettoken --help
    - test -x ${PREFIX}/bin/htdecodetoken  # [unix]
    - test -x ${PREFIX}/bin/htdestroytoken  # [unix]
    - test -x ${PREFIX}/bin/httokensh  # [unix]

about:
  home: https://github.com/fermitools/htgettoken
  dev_url: https://github.com/fermitools/htgettoken.git
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  summary: Get OIDC bearer tokens by interacting with Hashicorp vault
  description: |
    htgettoken gets OIDC bearer tokens by interacting with Hashicorp vault

extra:
  recipe-maintainers:
    - duncanmmacleod
    - beckermr
