{% set name = "htgettoken" %}
{% set version = "1.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/fermitools/htgettoken/archive/v{{ version }}.tar.gz
  sha256: 01ebc56f94f930bcc16ad1ea217fb2d04a6d087c9cece761b4e962a112735696

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
  run:
    - jq
    - m2crypto
    - paramiko
    - pykerberos  # [not win]
    - pyopenssl
    - python
    - winkerberos  # [win]

test:
  commands:
    - htgettoken --help
    - test -x ${PREFIX}/bin/httokendecode  # [unix]

about:
  home: https://github.com/fermitools/htgettoken
  dev_url: https://github.com/fermitools/htgettoken.git
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  summary: Get OIDC bearer tokens by interacting with Hashicorp vault
  description: |
    htgettoken gets OIDC bearer tokens by interacting with Hashicorp vault

extra:
  recipe-maintainers:
    - duncanmmacleod
