{% set name = "htgettoken" %}
{% set version = "2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/fermitools/htgettoken/archive/v{{ version }}.tar.gz
  sha256: 0178e6ae14a9768c981f66bc9e68b99164a094ecf3120854eb23a5a9cef1763d

build:
  entry_points:
    - htgettoken = htgettoken:main
  number: 1
  skip: true  # [win]

requirements:
  build:
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
  host:
    - pip
    - python
    - setuptools >=30.3.0
    - wheel
  run:
    - jq
    - paramiko
    - python
    - python-gssapi
    - urllib3

test:
  requires:
    - pip
  imports:
    - htgettoken
  commands:
    # check metadata
    - python -m pip check
    - python -m pip show htgettoken
    # test scripts
    - htgettoken --help
    - test -x ${PREFIX}/bin/htdecodetoken  # [unix]
    - test -x ${PREFIX}/bin/htdestroytoken  # [unix]
    - test -x ${PREFIX}/bin/httokensh  # [unix]

about:
  home: https://github.com/fermitools/htgettoken
  dev_url: https://github.com/fermitools/htgettoken.git
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  summary: Get OIDC bearer tokens by interacting with Hashicorp vault
  description: |
    htgettoken gets OIDC bearer tokens by interacting with Hashicorp vault

extra:
  recipe-maintainers:
    - duncanmmacleod
    - beckermr
